apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test.api
  description: The demo API
  tags:
    - rest
  links:
    - url: https://github.com/amal-chacko-7/backstage-yml/edit/main/test-api.yaml
      title: GitHub Repo
      icon: github
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Test API
      license:
        name: MIT
    servers:
      - url: http://localhost:5000
    paths:
      /:
        get:
          summary: Print number
          operationId: printNumber
          tags:
            - number
          parameters:
            - name: number
              in: query
              description: Get number
              required: false
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: A paged array of pets
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Success"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Success:
          type: object
          required:
            - number
          properties:
            number:
              type: string
        Error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
